### PR TITLE
Spelling and "--insert v --create" fixes

### PR DESCRIPTION
**Pull request by rutheferd**
Made minor spelling fixes.

In the create examples `--insert` was used instead of `--create`.

### CODE REVIEW

**Comment by craigthomasfrost** [comment]
I think you probably meant this for the main docs repo @rutheferd? This is a very nascent prototype for future docs. Even then, I don't believe that PRs are used/useful on the main docs repo because the content is actually in another tool. Tagging @contenuto in case I'm wrong about workflows for content suggestions, but content in this repo is just dummy content. If this change needs to be made on the live/production docs, I'd open an issue there or post in #docs on Slack.

**Comment by craigthomasfrost** [comment]
I mean I can also merge this, just FYI that it won't have an impact on anything in production.

**Comment by rutheferd** [comment]
@craigthomasfrost Ahhhh got you! Seemed like this was the most complete and representative of the current docs. I will go the slack route!

**Comment by craigthomasfrost** [comment]
NP 🙂 closing this PR!

**Pull request closed without merging**
